### ISSUE TITLE
Feature: Ergebnissliste - Sortierung nach Datum und Uhrzeit ermöglichen

### ISSUE THREAD

**Issue by tobiasgraeber** [maschhoff/prpdf#21]
Vorschlag: Uhrzeit in Sortierung mit aufnehmen

**Comment by maschhoff** [comment]
Hey, meinst Du das?

![image](https://github.com/user-attachments/assets/6e389d14-e548-4ec4-a1cc-4dea9d74415e)

**Comment by maschhoff** [comment]
changed to date and time in latest-dev
